name = "jimi421-art"
account_id = "698917d9ae04da2587d19eaae5bcef5c"
compatibility_date = "2025-05-09"
main = "worker/index.js"

[[kv_namespaces]]
binding = "GALLERY_KV"
id = "339332424b3c47529ccf6e5d9528b2e8"

[[r2_buckets]]
binding = "ART_BUCKET"
bucket_name = "jimi421-art-r2"
